// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlOpvykNbrY3lp9vywxMwYcFYRcStO2_8',
    appId: '1:768069262363:web:e9bf2b0b73c9682f4e2cbe',
    messagingSenderId: '768069262363',
    projectId: 'mynotes-personal-project',
    authDomain: 'mynotes-personal-project.firebaseapp.com',
    storageBucket: 'mynotes-personal-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgqVQc-GKW13-8lf4t2T42D92CGHxcEEk',
    appId: '1:768069262363:android:55859797f343dc024e2cbe',
    messagingSenderId: '768069262363',
    projectId: 'mynotes-personal-project',
    storageBucket: 'mynotes-personal-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHyaLqJvuvVN9ARwIUtxvOzf8IZCOfcww',
    appId: '1:768069262363:ios:57563b57a12fe37e4e2cbe',
    messagingSenderId: '768069262363',
    projectId: 'mynotes-personal-project',
    storageBucket: 'mynotes-personal-project.appspot.com',
    iosClientId: '768069262363-8braqcllknf926480gdf7pco201b7kjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHyaLqJvuvVN9ARwIUtxvOzf8IZCOfcww',
    appId: '1:768069262363:ios:57563b57a12fe37e4e2cbe',
    messagingSenderId: '768069262363',
    projectId: 'mynotes-personal-project',
    storageBucket: 'mynotes-personal-project.appspot.com',
    iosClientId: '768069262363-8braqcllknf926480gdf7pco201b7kjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
